let readyMadeItems = [
  {
    id: "qwer",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product2.png",
    addtocart: "add to cart",
  },
  {
    id: "qwret",
    name: "Office Shirt",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product3.png",
    addtocart: "add to cart",
  },
  {
    id: "asaf",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product4.png",
    addtocart: "add to cart",
  },
  {
    id: "dhhfh",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "hlklj",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum die vieiue ieineunr ienr vinerine hjvbejrg ieuri eriuer olor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "zxcv",
    name: "Mens Suit",
    price: 11100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "vbnn",
    name: "Mens Suit",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "nkfd",
    name: "Mens Suit",
    price: 330,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "bwjdj",
    name: "Mens Suit",
    price: 330,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
  {
    id: "dksuuc",
    name: "Mens Suit",
    price: 330,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/product6.png",
    addtocart: "add to cart",
  },
];
